/* AUTO-GENERATED BY tools/sync-flow-book.c - DO NOT EDIT MANUALLY */
#ifndef FLOW_GENERATED_BOOK_KNOWLEDGE_H
#define FLOW_GENERATED_BOOK_KNOWLEDGE_H

#include "flowy.h"
#include <string.h>

#define FLOW_BOOK_CHAPTER_COUNT 15

typedef struct {
    const char *chapter_ref;
    const char *chapter_title;
    const char *philosophy_why;
    const char *book_excerpt;
} FlowBookChapterDoc;

static const FlowBookChapterDoc FLOW_BOOK_CHAPTERS_ZH[FLOW_BOOK_CHAPTER_COUNT] = {
    {
        .chapter_ref = "ch01_what_is_flow.md",
        .chapter_title = "第一章：什麼是 FLOW？ (從靜態編譯到動態活體系統的典範轉移)",
        .philosophy_why = "我們不是在編譯一份死沉沉的程式碼，而是在孕育一個能夠感知環境、自我退火、在毀滅性壓力下自我蛻變的拓樸活體。",
        .book_excerpt = "自 1957 年 Fortran 編譯器問世以來，編譯器架構的核心假設始終如一：原始碼是唯一真理。FLOW 徹底顛覆此一假設，將代碼視為可感知環境與持續演化的活體幾何流形。"
    },
    {
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "第二章：意圖規格 .flow (我們只向宇宙宣告幾何約束，不寫邏輯)",
        .philosophy_why = "在 FLOW 的哲學中，撰寫程式碼不是告訴 CPU 如何一步一步執行指令，而是向宇宙宣告系統必須服從的幾何邊界與不變量。",
        .book_excerpt = "一個標準的 .flow 描述檔是純宣告式的，不包含命令式迴圈或指標操作。開發者只宣告 input 規模、flow 流水線與物理約束，實作由引擎自動坍縮合成。"
    },
    {
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "第三章：拓樸圖譜 (將程式碼降維成可推算的依賴約束流形)",
        .philosophy_why = "軟體的架構不是文字檔目錄的堆疊，而是一張高維拓樸圖。在 FLOW 中，程式碼被降維成可直接進行圖論運算、親和性分析與遙測附著的活體神經圖譜。",
        .book_excerpt = "FLOW 將核心模組、驅動、元件與意圖統構為 FlowTopologyGraph，實施嚴格的分層防火牆審計、動態神經遙測附著與零跨層滲漏保證。"
    },
    {
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：BMF 最佳化與 1-Bit 混沌退火 (BitManifold BMF 暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "第五章：形式化最高法院 (SMT 4 大定理 UNSAT 證明與 1-Cycle 修剪)",
        .philosophy_why = "啟發式搜尋可以天馬行空，但發射出的每一行機器碼必須擁有無可爭辯的數學證明。SMT 定理證明器是 FLOW 宇宙的最高法院，凡無證明者，一律否決。",
        .book_excerpt = "SMT 最高法院透過 QF_LIA 理論驗證緩衝區邊界、記憶體配額上限、分片隔離與確定性 4 大定理。合約檢查與硬體邊界在編譯期即刻生成 1-Cycle 多面體位元修剪遮罩。"
    },
    {
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "第六章：JIT 代碼發射與幾何變形 (AoS 到 SoA 即時重映射與生存模式)",
        .philosophy_why = "程式碼不是雕刻在石頭上的死文字，而是能在記憶體中自發變形的黏土。當記憶體即將崩潰時，系統在微秒內完成拓樸幾何變形，躲過 OS OOM Killer 的致命屠刀。",
        .book_excerpt = "JIT 發射器支援 C、Rust、Python 與 LLVM IR 多目標。透過 mremap 實現 AoS 與 SoA 零拷貝即時切換；在極端低記憶體下自我否決 JIT，遁入零分配 Static Survival 避難所。"
    },
    {
        .chapter_ref = "ch07_qsbr_lockfree_hotswap.md",
        .chapter_title = "第七章：QSBR 零鎖熱替換 (微秒級世代指針遷移與 Watchdog 隔離)",
        .philosophy_why = "在每秒數千萬次請求的高並發伺服器中，獲取哪怕一把讀寫鎖（RWLock）都會造成災難性的快取一致性風暴。FLOW 採用統一 QSBR 無鎖架構，實現了讀取路徑零原子寫入、熱替換微秒級無損遷移。",
        .book_excerpt = "QSBR 透過靜態世代演進實現 >390M ops/s 讀取吞吐量。看門狗以 mprotect 隔離掉隊讀者執行緒，以客製化信號捕捉保證優雅降級與 0 丟失請求熱替換。"
    },
    {
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "第九章：大一統 .fvec 與 Universal Lockfile (架構權重庫、零秒冷啟動與抗體昇華)",
        .philosophy_why = "大腦負責即時推論，而 .fvec 是大腦裡的長期記憶神經權重。它既是具備 SMT 物理簽章的 Universal Lockfile，也是在戰火中自主長出肌肉記憶的抗體庫。",
        .book_excerpt = "大一統 .fvec 採用 1024-Byte 明文 ASCII 表頭 + CRC32 載荷。1ms 硬體親和度門禁杜絕跨架構無效套用；在線 100 萬次請求零錯誤與 SMT 認證觸發抗體昇華與赫布強化。"
    },
    {
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "第十章：決定論因果推論大腦 (0% 幻覺的架構自省、神經遙測熱點與職責分離)",
        .philosophy_why = "我們不需要一個會胡言亂語的機率型 Chatbot 來解釋系統架構。FLOW 打造了 Flowy——一個內建於二進位中、100% 決定論、零幻覺的代碼庫因果推論大腦。",
        .book_excerpt = "Flowy 嚴格遵循大腦（flowy.c）、審計設施（audit.c）與前端表現層（flowy_cli.c）三層分離。即時解析決策因果（flowy why）、神經遙測熱點（flowy bottleneck）與反事實模擬。"
    },
    {
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "第十一章：Level 5 絕對死局壓測與效能基準 (並發風暴與 OOM 雙重束縛下的生存實錄)",
        .philosophy_why = "在科林丸號（Kobayashi Maru）測試中，學員面臨註定毀滅的死局。FLOW 打造了 Level 5 絕對死局壓測：當記憶體暴跌 99%、連線暴增 10,000 倍時，系統在死局中自我蛻變求生。",
        .book_excerpt = "Level-5 熔爐壓測驗證了系統在雙重束縛下的 5 階段自癒過程，維持 0 封包丟失與 0 崩潰；QSBR 讀取吞吐達到 390M ops/s，通用鎖定檔套用耗時縮短至 37 微秒。"
    },
    {
        .chapter_ref = "ch12_token_ring_and_embodied_coordination.md",
        .chapter_title = "第十二章：BMF Token Ring 離散注意力算子與具身知覺超幾何疊加",
        .philosophy_why = "知覺不是將世界的每一縷光子全數拷貝，而是以超幾何遮罩投影出可行生存子空間；雙重束縛下在 O(1) 內歸於靜態生存支撐。",
        .book_excerpt = "Token 環以離散注意力算子 Canvas_{t+1} = Phi(Canvas_t (x) Mask_Attn) 循環演化，收斂至固定點吸引子。64-bit 具身子空間切片與多感官遮罩超幾何疊加，在極端衝突下啟動靜態生存支撐態。"
    },
    {
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "第十三章：六大數學支柱：經驗啟發式的全息消解",
        .philosophy_why = "凡充斥經驗常數與魔術數字之處，皆是脆弱的避難所。FLOW 以多面體模型、OCO、Lyapunov、勢能博弈、Moreau 掃掠與單純同調論徹底取代工程猜測。",
        .book_excerpt = "六大數學支柱消滅了編譯器展開、快取淘汰、重試退避、網格排程、防抖計時器與盲目 Fuzzing 的經驗 Heuristics，使全系統收斂至堅實的數學定理下限。"
    },
    {
        .chapter_ref = "ch14_structural_entropy_elimination.md",
        .chapter_title = "第十四章：擠乾軟體工程水分：零缺陷數學結構",
        .philosophy_why = "程式碼行數即系統結構熵 K(S)。FLOW 擠乾配置器分級、防禦性 Null 檢查瀑布、序列化與日誌字串格式化等軟體工程水分，達成柯爾莫哥洛夫理論下限。",
        .book_excerpt = "以幾何 Bump-Pointer+QSBR 世代折疊消滅 Slab 分配器；Curry-Howard 同構使防禦性檢查死碼消除；同構記憶體切片實現 0ns 傳輸；語義哈希流形消除熱路徑 snprintf；仿射測地線消除引用計數與 GC。"
    },
    {
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "第十五章：流形代數、神經-符號橋、時空光錐反事實預演與活體自創生",
        .philosophy_why = "約束收斂即相關。統計相關性只是幾何約束在投影維度上的影子；FLOW 抓的是本體，傳統 ML 抓的是影子。",
        .book_excerpt = "流形代數實現交集與連鎖基因萃取；神經符號橋在 14 週期內完成 4096-D 語義到物理多面體投影；時空光錐預演未來 3 秒黑天鵝並在 13 微秒內混沌退火修正；物種形成引擎實現 10,000 節點活體自創生。"
    }

};

static const FlowBookChapterDoc FLOW_BOOK_CHAPTERS_EN[FLOW_BOOK_CHAPTER_COUNT] = {
    {
        .chapter_ref = "ch01_what_is_flow.md",
        .chapter_title = "Chapter 1: What is FLOW? (Paradigm Shift from Static Compiler to Living System)",
        .philosophy_why = "We are not compiling dead code, but nurturing an autopoietic topological organism that senses environment, anneals autonomously, and morphs under destructive stress.",
        .book_excerpt = "Since the 1957 Fortran compiler, the assumption has been that source code is static truth. FLOW inverts this: code declares immutable geometric boundaries, while the runtime organism evolves on manifolds."
    },
    {
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "Chapter 2: Intent vs. Implementation (.flow: We Declare Invariants, Not Logic)",
        .philosophy_why = "In FLOW philosophy, writing code is not telling the CPU step-by-step instructions, but declaring the geometric boundaries and mathematical invariants the universe must obey.",
        .book_excerpt = "A standard .flow spec is strictly declarative with no imperative loops or manual pointers. Developers declare input bounds and pipeline topology, letting the engine synthesize optimal implementations."
    },
    {
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "Chapter 3: Topology Graph (Dimensionality Reduction into Computable Invariants)",
        .philosophy_why = "Software architecture is not a stack of directory text files, but a high-dimensional topology graph computed via graph theory, shard affinity, and neural telemetry.",
        .book_excerpt = "FLOW models compiler core, drivers, components, and intent as a unified FlowTopologyGraph, enforcing strict layer firewalls with 0 cross-layer architectural leaks."
    },
    {
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing & BitManifold (BMF) (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "Chapter 5: Formal Supreme Court (SMT 4-Theorem UNSAT Proofs & 1-Cycle Pruning)",
        .philosophy_why = "Heuristic search can explore freely, but every emitted line of machine code must have indisputable mathematical proofs. The SMT solver is the Supreme Court: unproven plans are vetoed.",
        .book_excerpt = "SMT proves buffer bounds, memory quotas, shard isolation, and determinism via QF_LIA. Contract and resource bounds immediately synthesize 1-cycle bitwise pruning masks."
    },
    {
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "Chapter 6: JIT Emission & Geometric Morphing (AoS to SoA Remapping & Survival Mode)",
        .philosophy_why = "Code is not carved in stone, but clay morphing in memory. When RAM collapses, the system executes microsecond geometric morphing to escape the OS OOM Killer.",
        .book_excerpt = "JIT emitter targets C, Rust, Python, and LLVM IR. mremap enables zero-copy AoS <-> SoA morphing. Under stress, self-aware JIT vetoes compilation and routes traffic to Static Survival shelters."
    },
    {
        .chapter_ref = "ch07_qsbr_lockfree_hotswap.md",
        .chapter_title = "Chapter 7: QSBR Lock-Free Hot-Swap (Sub-Microsecond Generational Migration)",
        .philosophy_why = "In servers processing millions of requests/sec, acquiring even one RWLock triggers catastrophic cache-line bouncing. FLOW QSBR achieves zero atomic writes on read paths and sub-microsecond migration.",
        .book_excerpt = "QSBR achieves >390M ops/s read throughput. Epoch watchdogs isolate stragglers via mprotect, guaranteeing graceful degradation and 0 dropped requests during hot-swap."
    },
    {
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "Chapter 9: Universal .fvec & Lockfiles (Architecture Weights, Zero-Cold-Start & Antibodies)",
        .philosophy_why = "The brain infers in real time, while .fvec stores long-term architecture weights. It serves as a Universal Lockfile with SMT signatures and an immune antibody repository.",
        .book_excerpt = "Universal .fvec pairs a 1024-byte ASCII header with CRC32 binary payload. A 1ms affinity gate rejects incompatible architectures; 1M zero-error online requests trigger autonomous antibody promotion."
    },
    {
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "Chapter 10: Deterministic Flowy Reasoner (0% Hallucination Introspection & Decoupling)",
        .philosophy_why = "We do not need a hallucinating probabilistic chatbot to explain system architecture. FLOW built Flowy: a 100% deterministic, zero-hallucination causal codebase reasoner in pure C.",
        .book_excerpt = "Flowy decouples Brain (flowy.c), Audit Logger (audit.c), and CLI Presentation (flowy_cli.c). It provides deterministic causal explanations (flowy why), telemetry diagnosis, and what-if simulation."
    },
    {
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "Chapter 11: Level 5 Crucible & Benchmarks (Kobayashi Maru & Production Replay)",
        .philosophy_why = "In Kobayashi Maru double-bind crises where memory drops 99% amid 10,000x traffic surges, FLOW demonstrates Level-5 resilience via SMT veto, JIT shelter, and QSBR zero-downtime morphing.",
        .book_excerpt = "The Level-5 crucible validates 5-stage autonomous self-healing with 0 dropped requests and 0 panics. QSBR achieves >390M ops/s read throughput and 37us instant cold-start application."
    },
    {
        .chapter_ref = "ch12_token_ring_and_embodied_coordination.md",
        .chapter_title = "Chapter 12: BMF Token Ring Attention Operator & Embodied Perceptual Coordination",
        .philosophy_why = "Perception does not copy raw sensory noise; it projects feasible survival manifolds via hypergeometric masks, collapsing to an emergency brace under double-binds in O(1).",
        .book_excerpt = "The Token Ring evolves via discrete attention operator Canvas_{t+1} = Phi(Canvas_t (x) Mask_Attn), converging to a Lyapunov attractor fixed point. 64-bit coordinate slicing and multi-sensory mask superposition ensure sound physical stability."
    },
    {
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "Chapter 13: The Six Mathematical Pillars (Eliminating Empirical Heuristics)",
        .philosophy_why = "Wherever magic numbers and heuristics reside is a sanctuary of system fragility. FLOW eliminates engineering guesswork through rigorous mathematical pillars.",
        .book_excerpt = "Six mathematical pillars replace loop unrolling, cache eviction, backpressure, mesh routing, anti-flapping debounce, and mutation fuzzing with formal theorems and provable bounds."
    },
    {
        .chapter_ref = "ch14_structural_entropy_elimination.md",
        .chapter_title = "Chapter 14: Structural Entropy Elimination (6 Zero-Defect Mathematical Paradigms)",
        .philosophy_why = "Lines of code measure system structural entropy K(S). FLOW purges boilerplate software engineering complexities and reaches the Kolmogorov complexity theoretical lower bound.",
        .book_excerpt = "Bump-Pointer QSBR eliminates allocator fragmentation; Curry-Howard SMT DCE purges defensive null checks; Isomorphic wire slicing provides 0ns parsing; Semantic event manifolds eliminate hot-path snprintf; Affine geodesics eliminate ref-counting and GC."
    },
    {
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "Chapter 15: Manifold Algebra, Neuro-Bit Bridge, Spacetime Pre-Play & Swarm Autopoiesis",
        .philosophy_why = "Constraint convergence is correlation. Statistical correlation is merely a shadow of physical geometric constraints projected onto observation dimensions.",
        .book_excerpt = "Manifold algebra executes feasible intersection and epistasis derivation; Neuro-bit bridge projects 4096-D continuous embeddings to polyhedra in 14 cycles; Spacetime preplay avers black swans in 13 microseconds; Swarm speciation engine enables autopoiesis across 10,000 nodes."
    }

};

typedef struct {
    const char *module_id;
    const char *chapter_ref;
    const char *chapter_title;
    const char *philosophy_why;
    const char *book_excerpt;
} FlowModuleBookBinding;

static const FlowModuleBookBinding FLOW_MODULE_BOOK_BINDINGS_ZH[42] = {
    {
        .module_id = "flowc",
        .chapter_ref = "ch01_what_is_flow.md",
        .chapter_title = "第一章：什麼是 FLOW？ (從靜態編譯到動態活體系統的典範轉移)",
        .philosophy_why = "我們不是在編譯一份死沉沉的程式碼，而是在孕育一個能夠感知環境、自我退火、在毀滅性壓力下自我蛻變的拓樸活體。",
        .book_excerpt = "自 1957 年 Fortran 編譯器問世以來，編譯器架構的核心假設始終如一：原始碼是唯一真理。FLOW 徹底顛覆此一假設，將代碼視為可感知環境與持續演化的活體幾何流形。"
    },
    {
        .module_id = "parser",
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "第二章：意圖規格 .flow (我們只向宇宙宣告幾何約束，不寫邏輯)",
        .philosophy_why = "在 FLOW 的哲學中，撰寫程式碼不是告訴 CPU 如何一步一步執行指令，而是向宇宙宣告系統必須服從的幾何邊界與不變量。",
        .book_excerpt = "一個標準的 .flow 描述檔是純宣告式的，不包含命令式迴圈或指標操作。開發者只宣告 input 規模、flow 流水線與物理約束，實作由引擎自動坍縮合成。"
    },
    {
        .module_id = "semantic",
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "第二章：意圖規格 .flow (我們只向宇宙宣告幾何約束，不寫邏輯)",
        .philosophy_why = "在 FLOW 的哲學中，撰寫程式碼不是告訴 CPU 如何一步一步執行指令，而是向宇宙宣告系統必須服從的幾何邊界與不變量。",
        .book_excerpt = "一個標準的 .flow 描述檔是純宣告式的，不包含命令式迴圈或指標操作。開發者只宣告 input 規模、flow 流水線與物理約束，實作由引擎自動坍縮合成。"
    },
    {
        .module_id = "topology",
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "第三章：拓樸圖譜 (將程式碼降維成可推算的依賴約束流形)",
        .philosophy_why = "軟體的架構不是文字檔目錄的堆疊，而是一張高維拓樸圖。在 FLOW 中，程式碼被降維成可直接進行圖論運算、親和性分析與遙測附著的活體神經圖譜。",
        .book_excerpt = "FLOW 將核心模組、驅動、元件與意圖統構為 FlowTopologyGraph，實施嚴格的分層防火牆審計、動態神經遙測附著與零跨層滲漏保證。"
    },
    {
        .module_id = "orchestrator",
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "第三章：拓樸圖譜 (將程式碼降維成可推算的依賴約束流形)",
        .philosophy_why = "軟體的架構不是文字檔目錄的堆疊，而是一張高維拓樸圖。在 FLOW 中，程式碼被降維成可直接進行圖論運算、親和性分析與遙測附著的活體神經圖譜。",
        .book_excerpt = "FLOW 將核心模組、驅動、元件與意圖統構為 FlowTopologyGraph，實施嚴格的分層防火牆審計、動態神經遙測附著與零跨層滲漏保證。"
    },
    {
        .module_id = "bitspace",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火與 BitManifold (BMF) (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .module_id = "search",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火與 BitManifold (BMF) (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .module_id = "swarm",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火與 BitManifold (BMF) (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .module_id = "genetic",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火與 BitManifold (BMF) (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .module_id = "smt",
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "第五章：形式化最高法院 (SMT 4 大定理 UNSAT 證明與 1-Cycle 修剪)",
        .philosophy_why = "啟發式搜尋可以天馬行空，但發射出的每一行機器碼必須擁有無可爭辯的數學證明。SMT 定理證明器是 FLOW 宇宙的最高法院，凡無證明者，一律否決。",
        .book_excerpt = "SMT 最高法院透過 QF_LIA 理論驗證緩衝區邊界、記憶體配額上限、分片隔離與確定性 4 大定理。合約檢查與硬體邊界在編譯期即刻生成 1-Cycle 多面體位元修剪遮罩。"
    },
    {
        .module_id = "verifier",
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "第五章：形式化最高法院 (SMT 4 大定理 UNSAT 證明與 1-Cycle 修剪)",
        .philosophy_why = "啟發式搜尋可以天馬行空，但發射出的每一行機器碼必須擁有無可爭辯的數學證明。SMT 定理證明器是 FLOW 宇宙的最高法院，凡無證明者，一律否決。",
        .book_excerpt = "SMT 最高法院透過 QF_LIA 理論驗證緩衝區邊界、記憶體配額上限、分片隔離與確定性 4 大定理。合約檢查與硬體邊界在編譯期即刻生成 1-Cycle 多面體位元修剪遮罩。"
    },
    {
        .module_id = "jit",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "第六章：JIT 代碼發射與幾何變形 (AoS 到 SoA 即時重映射與生存模式)",
        .philosophy_why = "程式碼不是雕刻在石頭上的死文字，而是能在記憶體中自發變形的黏土。當記憶體即將崩潰時，系統在微秒內完成拓樸幾何變形，躲過 OS OOM Killer 的致命屠刀。",
        .book_excerpt = "JIT 發射器支援 C、Rust、Python 與 LLVM IR 多目標。透過 mremap 實現 AoS 與 SoA 零拷貝即時切換；在極端低記憶體下自我否決 JIT，遁入零分配 Static Survival 避難所。"
    },
    {
        .module_id = "adaptive",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "第六章：JIT 代碼發射與幾何變形 (AoS 到 SoA 即時重映射與生存模式)",
        .philosophy_why = "程式碼不是雕刻在石頭上的死文字，而是能在記憶體中自發變形的黏土。當記憶體即將崩潰時，系統在微秒內完成拓樸幾何變形，躲過 OS OOM Killer 的致命屠刀。",
        .book_excerpt = "JIT 發射器支援 C、Rust、Python 與 LLVM IR 多目標。透過 mremap 實現 AoS 與 SoA 零拷貝即時切換；在極端低記憶體下自我否決 JIT，遁入零分配 Static Survival 避難所。"
    },
    {
        .module_id = "backend",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "第六章：JIT 代碼發射與幾何變形 (AoS 到 SoA 即時重映射與生存模式)",
        .philosophy_why = "程式碼不是雕刻在石頭上的死文字，而是能在記憶體中自發變形的黏土。當記憶體即將崩潰時，系統在微秒內完成拓樸幾何變形，躲過 OS OOM Killer 的致命屠刀。",
        .book_excerpt = "JIT 發射器支援 C、Rust、Python 與 LLVM IR 多目標。透過 mremap 實現 AoS 與 SoA 零拷貝即時切換；在極端低記憶體下自我否決 JIT，遁入零分配 Static Survival 避難所。"
    },
    {
        .module_id = "reload",
        .chapter_ref = "ch07_qsbr_lockfree_hotswap.md",
        .chapter_title = "第七章：QSBR 零鎖熱替換 (微秒級世代指針遷移與 Watchdog 隔離)",
        .philosophy_why = "在每秒數千萬次請求的高並發伺服器中，獲取哪怕一把讀寫鎖（RWLock）都會造成災難性的快取一致性風暴。FLOW 採用統一 QSBR 無鎖架構，實現了讀取路徑零原子寫入、熱替換微秒級無損遷移。",
        .book_excerpt = "QSBR 透過靜態世代演進實現 >390M ops/s 讀取吞吐量。看門狗以 mprotect 隔離掉隊讀者執行緒，以客製化信號捕捉保證優雅降級與 0 丟失請求熱替換。"
    },
    {
        .module_id = "primitive",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "abi",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "registry",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "security",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "embodied",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "flowy_fvec",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "第九章：大一統 .fvec 與 Universal Lockfile (架構權重庫、零秒冷啟動與抗體昇華)",
        .philosophy_why = "大腦負責即時推論，而 .fvec 是大腦裡的長期記憶神經權重。它既是具備 SMT 物理簽章的 Universal Lockfile，也是在戰火中自主長出肌肉記憶的抗體庫。",
        .book_excerpt = "大一統 .fvec 採用 1024-Byte 明文 ASCII 表頭 + CRC32 載荷。1ms 硬體親和度門禁杜絕跨架構無效套用；在線 100 萬次請求零錯誤與 SMT 認證觸發抗體昇華與赫布強化。"
    },
    {
        .module_id = "fvec",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "第九章：大一統 .fvec 與 Universal Lockfile (架構權重庫、零秒冷啟動與抗體昇華)",
        .philosophy_why = "大腦負責即時推論，而 .fvec 是大腦裡的長期記憶神經權重。它既是具備 SMT 物理簽章的 Universal Lockfile，也是在戰火中自主長出肌肉記憶的抗體庫。",
        .book_excerpt = "大一統 .fvec 採用 1024-Byte 明文 ASCII 表頭 + CRC32 載荷。1ms 硬體親和度門禁杜絕跨架構無效套用；在線 100 萬次請求零錯誤與 SMT 認證觸發抗體昇華與赫布強化。"
    },
    {
        .module_id = "vault",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "第九章：大一統 .fvec 與 Universal Lockfile (架構權重庫、零秒冷啟動與抗體昇華)",
        .philosophy_why = "大腦負責即時推論，而 .fvec 是大腦裡的長期記憶神經權重。它既是具備 SMT 物理簽章的 Universal Lockfile，也是在戰火中自主長出肌肉記憶的抗體庫。",
        .book_excerpt = "大一統 .fvec 採用 1024-Byte 明文 ASCII 表頭 + CRC32 載荷。1ms 硬體親和度門禁杜絕跨架構無效套用；在線 100 萬次請求零錯誤與 SMT 認證觸發抗體昇華與赫布強化。"
    },
    {
        .module_id = "flowy",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "第十章：決定論因果推論大腦 (0% 幻覺的架構自省、神經遙測熱點與職責分離)",
        .philosophy_why = "我們不需要一個會胡言亂語的機率型 Chatbot 來解釋系統架構。FLOW 打造了 Flowy——一個內建於二進位中、100% 決定論、零幻覺的代碼庫因果推論大腦。",
        .book_excerpt = "Flowy 嚴格遵循大腦（flowy.c）、審計設施（audit.c）與前端表現層（flowy_cli.c）三層分離。即時解析決策因果（flowy why）、神經遙測熱點（flowy bottleneck）與反事實模擬。"
    },
    {
        .module_id = "flowy_cli",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "第十章：決定論因果推論大腦 (0% 幻覺的架構自省、神經遙測熱點與職責分離)",
        .philosophy_why = "我們不需要一個會胡言亂語的機率型 Chatbot 來解釋系統架構。FLOW 打造了 Flowy——一個內建於二進位中、100% 決定論、零幻覺的代碼庫因果推論大腦。",
        .book_excerpt = "Flowy 嚴格遵循大腦（flowy.c）、審計設施（audit.c）與前端表現層（flowy_cli.c）三層分離。即時解析決策因果（flowy why）、神經遙測熱點（flowy bottleneck）與反事實模擬。"
    },
    {
        .module_id = "audit",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "第十章：決定論因果推論大腦 (0% 幻覺的架構自省、神經遙測熱點與職責分離)",
        .philosophy_why = "我們不需要一個會胡言亂語的機率型 Chatbot 來解釋系統架構。FLOW 打造了 Flowy——一個內建於二進位中、100% 決定論、零幻覺的代碼庫因果推論大腦。",
        .book_excerpt = "Flowy 嚴格遵循大腦（flowy.c）、審計設施（audit.c）與前端表現層（flowy_cli.c）三層分離。即時解析決策因果（flowy why）、神經遙測熱點（flowy bottleneck）與反事實模擬。"
    },
    {
        .module_id = "benchmark",
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "第十一章：Level 5 絕對死局壓測與效能基準 (並發風暴與 OOM 雙重束縛下的生存實錄)",
        .philosophy_why = "在科林丸號（Kobayashi Maru）測試中，學員面臨註定毀滅的死局。FLOW 打造了 Level 5 絕對死局壓測：當記憶體暴跌 99%、連線暴增 10,000 倍時，系統在死局中自我蛻變求生。",
        .book_excerpt = "Level-5 熔爐壓測驗證了系統在雙重束縛下的 5 階段自癒過程，維持 0 封包丟失與 0 崩潰；QSBR 讀取吞吐達到 390M ops/s，通用鎖定檔套用耗時縮短至 37 微秒。"
    },
    {
        .module_id = "gateway",
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "第十一章：Level 5 絕對死局壓測與效能基準 (並發風暴與 OOM 雙重束縛下的生存實錄)",
        .philosophy_why = "在科林丸號（Kobayashi Maru）測試中，學員面臨註定毀滅的死局。FLOW 打造了 Level 5 絕對死局壓測：當記憶體暴跌 99%、連線暴增 10,000 倍時，系統在死局中自我蛻變求生。",
        .book_excerpt = "Level-5 熔爐壓測驗證了系統在雙重束縛下的 5 階段自癒過程，維持 0 封包丟失與 0 崩潰；QSBR 讀取吞吐達到 390M ops/s，通用鎖定檔套用耗時縮短至 37 微秒。"
    },
    {
        .module_id = "matching",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "cxl_fabric",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "token_ring",
        .chapter_ref = "ch12_token_ring_and_embodied_coordination.md",
        .chapter_title = "第十二章：BMF Token Ring 離散注意力算子與具身知覺超幾何疊加",
        .philosophy_why = "知覺不是將世界的每一縷光子全數拷貝，而是以超幾何遮罩投影出可行生存子空間；雙重束縛下在 O(1) 內歸於靜態生存支撐。",
        .book_excerpt = "Token 環以離散注意力算子循環演化，收斂至固定點吸引子。"
    },
    {
        .module_id = "polyhedral",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "第十三章：六大數學支柱：經驗啟發式的全息消解",
        .philosophy_why = "凡充斥經驗常數與魔術數字之處，皆是脆弱的避難所。FLOW 以六大數學支柱徹底取代工程猜測。",
        .book_excerpt = "Presburger 仿射約束多面體求解最優迴圈 Tiling 與 SIMD 寬度，消滅展開次數猜測。"
    },
    {
        .module_id = "oco_cache",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "第十三章：六大數學支柱：經驗啟發式的全息消解",
        .philosophy_why = "在線凸最佳化雙對偶拉格朗日求解影子價格，消滅經驗快取淘汰掃描。",
        .book_excerpt = "以超平面正交投影與邊際效用影子價格判定快取駐留，取代 LRU/LFU 啟發式。"
    },
    {
        .module_id = "lyapunov",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "第十三章：六大數學支柱：經驗啟發式的全息消解",
        .philosophy_why = "流體微分方程與 Lyapunov Banach 壓縮映射消滅盲目重試與抖動退避。",
        .book_excerpt = "隨機動力系統保證佇列以指數速度收斂至平衡態，Lipschitz 常數 L < 1。"
    },
    {
        .module_id = "potential_game",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "第十三章：六大數學支柱：經驗啟發式的全息消解",
        .philosophy_why = "Beckmann 勢能函數負梯度流收斂至 Wardrop 第一均衡，消滅工作竊取猜測。",
        .book_excerpt = "自組織分佈式調度使所有有效路徑邊際延遲完全相等，最小化全域擁塞。"
    },
    {
        .module_id = "moreau",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "第十三章：六大數學支柱：經驗啟發式的全息消解",
        .philosophy_why = "Moreau 掃掠過程幾何法錐吸收高頻擾動，消滅手寫防抖計時器。",
        .book_excerpt = "死區流形吞噬微小抖動，非平滑遲滯曲線阻絕邊界震盪假警報。"
    },
    {
        .module_id = "simplicial_homology",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "第十三章：六大數學支柱：經驗啟發式的全息消解",
        .philosophy_why = "代數拓撲邊界算子與非零貝蒂數定向引導光線，消滅隨機盲目 Fuzzing。",
        .book_excerpt = "d1 o d2 = 0 拓樸鏈複形驗證，b1 > 0 導航探索未穿透之狀態空間漏洞。"
    },
    {
        .module_id = "entropy_collapse",
        .chapter_ref = "ch14_structural_entropy_elimination.md",
        .chapter_title = "第十四章：擠乾軟體工程水分：零缺陷數學結構",
        .philosophy_why = "程式碼行數即系統結構熵 K(S)。FLOW 擠乾六大軟體工程水分，達到柯爾莫哥洛夫理論下限。",
        .book_excerpt = "Bump-Pointer QSBR、Curry-Howard SMT DCE、同構記憶體切片、相空間自創生、語義哈希流形與仿射測地線。"
    },
    {
        .module_id = "manifold_algebra",
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "第十五章：流形代數、神經-符號橋、時空光錐反事實預演與活體自創生",
        .philosophy_why = "約束收斂即相關。流形交集算子在多面體邊界自動萃取連鎖基因群。",
        .book_excerpt = "M_A (cap) M_B 緊縮邊界並依影子價格計算 Pareto 共識中心，Moreau 投影保證零缺陷。"
    },
    {
        .module_id = "neuro_bridge",
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "第十五章：流形代數、神經-符號橋、時空光錐反事實預演與活體自創生",
        .philosophy_why = "大模型負責理解世界，FLOW 負責物理防摔與微秒剛性執行。",
        .book_excerpt = "稀疏 Johnson-Lindenstrauss SIMD 投影在 14 週期內將 4096-D 語義向量映射為 BMF 座標與剛性多面體。"
    },
    {
        .module_id = "spacetime_preplay",
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "第十五章：流形代數、神經-符號橋、時空光錐反事實預演與活體自創生",
        .philosophy_why = "從當下安全到時空錐前瞻安全，消除數秒後潛伏的黑天鵝失穩。",
        .book_excerpt = "哈密頓相空間前瞻預演未來 3 秒光錐，13 微秒內以 1-Bit 混沌退火修正結冰側翻舵角。"
    },
    {
        .module_id = "swarm_autopoiesis",
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "第十五章：流形代數、神經-符號橋、時空光錐反事實預演與活體自創生",
        .philosophy_why = "軟體系統的活體自創生，自發湧現跨環境最適拓撲。",
        .book_excerpt = "四大生態位壓力下連鎖感知雜交與環境熵漂移，9-Byte 淋巴抗體網絡促進全網架構自動晉升。"
    }

};

static const FlowModuleBookBinding FLOW_MODULE_BOOK_BINDINGS_EN[42] = {
    {
        .module_id = "flowc",
        .chapter_ref = "ch01_what_is_flow.md",
        .chapter_title = "Chapter 1: What is FLOW? (Paradigm Shift from Static Compiler to Living System)",
        .philosophy_why = "We are not compiling dead code, but nurturing an autopoietic topological organism that senses environment, anneals autonomously, and morphs under destructive stress.",
        .book_excerpt = "Since the 1957 Fortran compiler, the assumption has been that source code is static truth. FLOW inverts this: code declares immutable geometric boundaries, while the runtime organism evolves on manifolds."
    },
    {
        .module_id = "parser",
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "Chapter 2: Intent vs. Implementation (.flow: We Declare Invariants, Not Logic)",
        .philosophy_why = "In FLOW philosophy, writing code is not telling the CPU step-by-step instructions, but declaring the geometric boundaries and mathematical invariants the universe must obey.",
        .book_excerpt = "A standard .flow spec is strictly declarative with no imperative loops or manual pointers. Developers declare input bounds and pipeline topology, letting the engine synthesize optimal implementations."
    },
    {
        .module_id = "semantic",
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "Chapter 2: Intent vs. Implementation (.flow: We Declare Invariants, Not Logic)",
        .philosophy_why = "In FLOW philosophy, writing code is not telling the CPU step-by-step instructions, but declaring the geometric boundaries and mathematical invariants the universe must obey.",
        .book_excerpt = "A standard .flow spec is strictly declarative with no imperative loops or manual pointers. Developers declare input bounds and pipeline topology, letting the engine synthesize optimal implementations."
    },
    {
        .module_id = "topology",
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "Chapter 3: Topology Graph (Dimensionality Reduction into Computable Invariants)",
        .philosophy_why = "Software architecture is not a stack of directory text files, but a high-dimensional topology graph computed via graph theory, shard affinity, and neural telemetry.",
        .book_excerpt = "FLOW models compiler core, drivers, components, and intent as a unified FlowTopologyGraph, enforcing strict layer firewalls with 0 cross-layer architectural leaks."
    },
    {
        .module_id = "orchestrator",
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "Chapter 3: Topology Graph (Dimensionality Reduction into Computable Invariants)",
        .philosophy_why = "Software architecture is not a stack of directory text files, but a high-dimensional topology graph computed via graph theory, shard affinity, and neural telemetry.",
        .book_excerpt = "FLOW models compiler core, drivers, components, and intent as a unified FlowTopologyGraph, enforcing strict layer firewalls with 0 cross-layer architectural leaks."
    },
    {
        .module_id = "bitspace",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing & BitManifold (BMF) (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .module_id = "search",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing & BitManifold (BMF) (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .module_id = "swarm",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing & BitManifold (BMF) (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .module_id = "genetic",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing & BitManifold (BMF) (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .module_id = "smt",
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "Chapter 5: Formal Supreme Court (SMT 4-Theorem UNSAT Proofs & 1-Cycle Pruning)",
        .philosophy_why = "Heuristic search can explore freely, but every emitted line of machine code must have indisputable mathematical proofs. The SMT solver is the Supreme Court: unproven plans are vetoed.",
        .book_excerpt = "SMT proves buffer bounds, memory quotas, shard isolation, and determinism via QF_LIA. Contract and resource bounds immediately synthesize 1-cycle bitwise pruning masks."
    },
    {
        .module_id = "verifier",
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "Chapter 5: Formal Supreme Court (SMT 4-Theorem UNSAT Proofs & 1-Cycle Pruning)",
        .philosophy_why = "Heuristic search can explore freely, but every emitted line of machine code must have indisputable mathematical proofs. The SMT solver is the Supreme Court: unproven plans are vetoed.",
        .book_excerpt = "SMT proves buffer bounds, memory quotas, shard isolation, and determinism via QF_LIA. Contract and resource bounds immediately synthesize 1-cycle bitwise pruning masks."
    },
    {
        .module_id = "jit",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "Chapter 6: JIT Emission & Geometric Morphing (AoS to SoA Remapping & Survival Mode)",
        .philosophy_why = "Code is not carved in stone, but clay morphing in memory. When RAM collapses, the system executes microsecond geometric morphing to escape the OS OOM Killer.",
        .book_excerpt = "JIT emitter targets C, Rust, Python, and LLVM IR. mremap enables zero-copy AoS <-> SoA morphing. Under stress, self-aware JIT vetoes compilation and routes traffic to Static Survival shelters."
    },
    {
        .module_id = "adaptive",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "Chapter 6: JIT Emission & Geometric Morphing (AoS to SoA Remapping & Survival Mode)",
        .philosophy_why = "Code is not carved in stone, but clay morphing in memory. When RAM collapses, the system executes microsecond geometric morphing to escape the OS OOM Killer.",
        .book_excerpt = "JIT emitter targets C, Rust, Python, and LLVM IR. mremap enables zero-copy AoS <-> SoA morphing. Under stress, self-aware JIT vetoes compilation and routes traffic to Static Survival shelters."
    },
    {
        .module_id = "backend",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "Chapter 6: JIT Emission & Geometric Morphing (AoS to SoA Remapping & Survival Mode)",
        .philosophy_why = "Code is not carved in stone, but clay morphing in memory. When RAM collapses, the system executes microsecond geometric morphing to escape the OS OOM Killer.",
        .book_excerpt = "JIT emitter targets C, Rust, Python, and LLVM IR. mremap enables zero-copy AoS <-> SoA morphing. Under stress, self-aware JIT vetoes compilation and routes traffic to Static Survival shelters."
    },
    {
        .module_id = "reload",
        .chapter_ref = "ch07_qsbr_lockfree_hotswap.md",
        .chapter_title = "Chapter 7: QSBR Lock-Free Hot-Swap (Sub-Microsecond Generational Migration)",
        .philosophy_why = "In servers processing millions of requests/sec, acquiring even one RWLock triggers catastrophic cache-line bouncing. FLOW QSBR achieves zero atomic writes on read paths and sub-microsecond migration.",
        .book_excerpt = "QSBR achieves >390M ops/s read throughput. Epoch watchdogs isolate stragglers via mprotect, guaranteeing graceful degradation and 0 dropped requests during hot-swap."
    },
    {
        .module_id = "primitive",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "abi",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "registry",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "security",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "embodied",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "flowy_fvec",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "Chapter 9: Universal .fvec & Lockfiles (Architecture Weights, Zero-Cold-Start & Antibodies)",
        .philosophy_why = "The brain infers in real time, while .fvec stores long-term architecture weights. It serves as a Universal Lockfile with SMT signatures and an immune antibody repository.",
        .book_excerpt = "Universal .fvec pairs a 1024-byte ASCII header with CRC32 binary payload. A 1ms affinity gate rejects incompatible architectures; 1M zero-error online requests trigger autonomous antibody promotion."
    },
    {
        .module_id = "fvec",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "Chapter 9: Universal .fvec & Lockfiles (Architecture Weights, Zero-Cold-Start & Antibodies)",
        .philosophy_why = "The brain infers in real time, while .fvec stores long-term architecture weights. It serves as a Universal Lockfile with SMT signatures and an immune antibody repository.",
        .book_excerpt = "Universal .fvec pairs a 1024-byte ASCII header with CRC32 binary payload. A 1ms affinity gate rejects incompatible architectures; 1M zero-error online requests trigger autonomous antibody promotion."
    },
    {
        .module_id = "vault",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "Chapter 9: Universal .fvec & Lockfiles (Architecture Weights, Zero-Cold-Start & Antibodies)",
        .philosophy_why = "The brain infers in real time, while .fvec stores long-term architecture weights. It serves as a Universal Lockfile with SMT signatures and an immune antibody repository.",
        .book_excerpt = "Universal .fvec pairs a 1024-byte ASCII header with CRC32 binary payload. A 1ms affinity gate rejects incompatible architectures; 1M zero-error online requests trigger autonomous antibody promotion."
    },
    {
        .module_id = "flowy",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "Chapter 10: Deterministic Flowy Reasoner (0% Hallucination Introspection & Decoupling)",
        .philosophy_why = "We do not need a hallucinating probabilistic chatbot to explain system architecture. FLOW built Flowy: a 100% deterministic, zero-hallucination causal codebase reasoner in pure C.",
        .book_excerpt = "Flowy decouples Brain (flowy.c), Audit Logger (audit.c), and CLI Presentation (flowy_cli.c). It provides deterministic causal explanations (flowy why), telemetry diagnosis, and what-if simulation."
    },
    {
        .module_id = "flowy_cli",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "Chapter 10: Deterministic Flowy Reasoner (0% Hallucination Introspection & Decoupling)",
        .philosophy_why = "We do not need a hallucinating probabilistic chatbot to explain system architecture. FLOW built Flowy: a 100% deterministic, zero-hallucination causal codebase reasoner in pure C.",
        .book_excerpt = "Flowy decouples Brain (flowy.c), Audit Logger (audit.c), and CLI Presentation (flowy_cli.c). It provides deterministic causal explanations (flowy why), telemetry diagnosis, and what-if simulation."
    },
    {
        .module_id = "audit",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "Chapter 10: Deterministic Flowy Reasoner (0% Hallucination Introspection & Decoupling)",
        .philosophy_why = "We do not need a hallucinating probabilistic chatbot to explain system architecture. FLOW built Flowy: a 100% deterministic, zero-hallucination causal codebase reasoner in pure C.",
        .book_excerpt = "Flowy decouples Brain (flowy.c), Audit Logger (audit.c), and CLI Presentation (flowy_cli.c). It provides deterministic causal explanations (flowy why), telemetry diagnosis, and what-if simulation."
    },
    {
        .module_id = "benchmark",
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "Chapter 11: Level 5 Crucible & Benchmarks (Kobayashi Maru & Production Replay)",
        .philosophy_why = "In Kobayashi Maru double-bind crises where memory drops 99% amid 10,000x traffic surges, FLOW demonstrates Level-5 resilience via SMT veto, JIT shelter, and QSBR zero-downtime morphing.",
        .book_excerpt = "The Level-5 crucible validates 5-stage autonomous self-healing with 0 dropped requests and 0 panics. QSBR achieves >390M ops/s read throughput and 37us instant cold-start application."
    },
    {
        .module_id = "gateway",
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "Chapter 11: Level 5 Crucible & Benchmarks (Kobayashi Maru & Production Replay)",
        .philosophy_why = "In Kobayashi Maru double-bind crises where memory drops 99% amid 10,000x traffic surges, FLOW demonstrates Level-5 resilience via SMT veto, JIT shelter, and QSBR zero-downtime morphing.",
        .book_excerpt = "The Level-5 crucible validates 5-stage autonomous self-healing with 0 dropped requests and 0 panics. QSBR achieves >390M ops/s read throughput and 37us instant cold-start application."
    },
    {
        .module_id = "matching",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "cxl_fabric",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "token_ring",
        .chapter_ref = "ch12_token_ring_and_embodied_coordination.md",
        .chapter_title = "Chapter 12: BMF Token Ring Attention Operator & Embodied Perceptual Coordination",
        .philosophy_why = "Perception does not copy raw sensory noise; it projects feasible survival manifolds via hypergeometric masks, collapsing to an emergency brace under double-binds in O(1).",
        .book_excerpt = "The Token Ring evolves via discrete attention operator Canvas_{t+1} = Phi(Canvas_t (x) Mask_Attn), converging to an attractor."
    },
    {
        .module_id = "polyhedral",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "Chapter 13: The Six Mathematical Pillars (Eliminating Empirical Heuristics)",
        .philosophy_why = "Wherever magic numbers and heuristics reside is a sanctuary of system fragility. FLOW eliminates engineering guesswork through rigorous mathematical pillars.",
        .book_excerpt = "Presburger affine integer polyhedra solve optimal loop tiling T* and SIMD width V*."
    },
    {
        .module_id = "oco_cache",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "Chapter 13: The Six Mathematical Pillars (Eliminating Empirical Heuristics)",
        .philosophy_why = "Online convex optimization and Lagrangian duality determine shadow price for eviction.",
        .book_excerpt = "Dual hyperplane projection eliminates heuristic cache eviction scans."
    },
    {
        .module_id = "lyapunov",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "Chapter 13: The Six Mathematical Pillars (Eliminating Empirical Heuristics)",
        .philosophy_why = "Fluid dynamics and Lyapunov Banach contraction eliminate blind backoff retries.",
        .book_excerpt = "Stochastic dynamical systems guarantee exponential convergence with Lipschitz L < 1."
    },
    {
        .module_id = "potential_game",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "Chapter 13: The Six Mathematical Pillars (Eliminating Empirical Heuristics)",
        .philosophy_why = "Beckmann potential negative gradient flow converges to Wardrop First Equilibrium.",
        .book_excerpt = "Equalized minimal latency across all active routes minimizes congestion."
    },
    {
        .module_id = "moreau",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "Chapter 13: The Six Mathematical Pillars (Eliminating Empirical Heuristics)",
        .philosophy_why = "Moreau sweeping process and non-smooth hysteresis geometric normal cones absorb flutters.",
        .book_excerpt = "Convex deadband absorbs noise fluctuations without arbitrary timer debounce."
    },
    {
        .module_id = "simplicial_homology",
        .chapter_ref = "ch13_six_mathematical_pillars.md",
        .chapter_title = "Chapter 13: The Six Mathematical Pillars (Eliminating Empirical Heuristics)",
        .philosophy_why = "Algebraic topology boundary operators and Betti numbers guide fuzzing into unexplored holes.",
        .book_excerpt = "d1 o d2 = 0 chain complex verification and b1 > 0 ray casting."
    },
    {
        .module_id = "entropy_collapse",
        .chapter_ref = "ch14_structural_entropy_elimination.md",
        .chapter_title = "Chapter 14: Structural Entropy Elimination (6 Zero-Defect Mathematical Paradigms)",
        .philosophy_why = "Lines of code measure system structural entropy K(S). FLOW purges boilerplate complexity.",
        .book_excerpt = "Bump-Pointer QSBR, Curry-Howard SMT DCE, Isomorphic Wire Slicing, BMF Autopoiesis, Semantic Event Manifolds, Affine Geodesics."
    },
    {
        .module_id = "manifold_algebra",
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "Chapter 15: Manifold Algebra, Neuro-Bit Bridge, Spacetime Pre-Play & Swarm Autopoiesis",
        .philosophy_why = "Constraint convergence is correlation. Manifold intersection automatically derives epistatic linkage groups.",
        .book_excerpt = "M_A (cap) M_B tightens boundaries and computes Pareto consensus centers; Moreau projection guarantees zero defects."
    },
    {
        .module_id = "neuro_bridge",
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "Chapter 15: Manifold Algebra, Neuro-Bit Bridge, Spacetime Pre-Play & Swarm Autopoiesis",
        .philosophy_why = "LLMs comprehend the world; FLOW enforces physical safety and microsecond rigid execution.",
        .book_excerpt = "Sparse Johnson-Lindenstrauss SIMD projection maps 4096-D continuous semantic embeddings to BMF and polyhedra in 14 cycles."
    },
    {
        .module_id = "spacetime_preplay",
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "Chapter 15: Manifold Algebra, Neuro-Bit Bridge, Spacetime Pre-Play & Swarm Autopoiesis",
        .philosophy_why = "From Now-Safe to Spacetime-Safe: eliminate black swan instabilities seconds before they materialize.",
        .book_excerpt = "Hamiltonian phase-space forward cone simulates future 3.0s, annealing rudder bias in 13 microseconds to avert ice slips."
    },
    {
        .module_id = "swarm_autopoiesis",
        .chapter_ref = "ch15_manifold_algebra_autopoiesis.md",
        .chapter_title = "Chapter 15: Manifold Algebra, Neuro-Bit Bridge, Spacetime Pre-Play & Swarm Autopoiesis",
        .philosophy_why = "Living software autopoiesis: spontaneous emergence of globally optimal topological architectures.",
        .book_excerpt = "Epistatic-linkage-aware crossover and adaptive entropy drift across 4 niches; 9-byte lymphatic fleet immunity."
    }

};

static inline const FlowModuleBookBinding *flow_book_lookup_binding_lang(const char *module_id, FlowLanguage lang) {
    if (module_id == NULL) return NULL;
    const FlowModuleBookBinding *bindings = (lang == FLOW_LANG_EN) ? FLOW_MODULE_BOOK_BINDINGS_EN : FLOW_MODULE_BOOK_BINDINGS_ZH;
    for (size_t i = 0; i < 42; ++i) {
        if (strcmp(bindings[i].module_id, module_id) == 0) return &bindings[i];
    }
    return NULL;
}

static inline const FlowModuleBookBinding *flow_book_lookup_binding(const char *module_id) {
    return flow_book_lookup_binding_lang(module_id, FLOW_LANG_ZH);
}

static inline const FlowBookChapterDoc *flow_book_lookup_chapter_lang(const char *ref_or_name, FlowLanguage lang) {
    if (ref_or_name == NULL) return NULL;
    const FlowBookChapterDoc *chapters = (lang == FLOW_LANG_EN) ? FLOW_BOOK_CHAPTERS_EN : FLOW_BOOK_CHAPTERS_ZH;
    for (size_t i = 0; i < FLOW_BOOK_CHAPTER_COUNT; ++i) {
        if (strcmp(chapters[i].chapter_ref, ref_or_name) == 0 || strstr(chapters[i].chapter_title, ref_or_name) != NULL) {
            return &chapters[i];
        }
    }
    return NULL;
}

static inline const FlowBookChapterDoc *flow_book_lookup_chapter(const char *ref_or_name) {
    return flow_book_lookup_chapter_lang(ref_or_name, FLOW_LANG_ZH);
}

#endif /* FLOW_GENERATED_BOOK_KNOWLEDGE_H */
