/* AUTO-GENERATED BY tools/sync-flow-book.c - DO NOT EDIT MANUALLY */
#ifndef FLOW_GENERATED_BOOK_KNOWLEDGE_H
#define FLOW_GENERATED_BOOK_KNOWLEDGE_H

#include "flowy.h"
#include <string.h>

#define FLOW_BOOK_CHAPTER_COUNT 11

typedef struct {
    const char *chapter_ref;
    const char *chapter_title;
    const char *philosophy_why;
    const char *book_excerpt;
} FlowBookChapterDoc;

static const FlowBookChapterDoc FLOW_BOOK_CHAPTERS_ZH[FLOW_BOOK_CHAPTER_COUNT] = {
    {
        .chapter_ref = "ch01_what_is_flow.md",
        .chapter_title = "第一章：什麼是 FLOW？ (從靜態編譯到動態活體系統的典範轉移)",
        .philosophy_why = "我們不是在編譯一份死沉沉的程式碼，而是在孕育一個能夠感知環境、自我退火、在毀滅性壓力下自我蛻變的拓樸活體。",
        .book_excerpt = "自 1957 年 Fortran 編譯器問世以來，編譯器架構的核心假設始終如一：原始碼是唯一真理。FLOW 徹底顛覆此一假設，將代碼視為可感知環境與持續演化的活體幾何流形。"
    },
    {
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "第二章：意圖規格 .flow (我們只向宇宙宣告幾何約束，不寫邏輯)",
        .philosophy_why = "在 FLOW 的哲學中，撰寫程式碼不是告訴 CPU 如何一步一步執行指令，而是向宇宙宣告系統必須服從的幾何邊界與不變量。",
        .book_excerpt = "一個標準的 .flow 描述檔是純宣告式的，不包含命令式迴圈或指標操作。開發者只宣告 input 規模、flow 流水線與物理約束，實作由引擎自動坍縮合成。"
    },
    {
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "第三章：拓樸圖譜 (將程式碼降維成可推算的依賴約束流形)",
        .philosophy_why = "軟體的架構不是文字檔目錄的堆疊，而是一張高維拓樸圖。在 FLOW 中，程式碼被降維成可直接進行圖論運算、親和性分析與遙測附著的活體神經圖譜。",
        .book_excerpt = "FLOW 將核心模組、驅動、元件與意圖統構為 FlowTopologyGraph，實施嚴格的分層防火牆審計、動態神經遙測附著與零跨層滲漏保證。"
    },
    {
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火 (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "第五章：形式化最高法院 (SMT 4 大定理 UNSAT 證明與 1-Cycle 修剪)",
        .philosophy_why = "啟發式搜尋可以天馬行空，但發射出的每一行機器碼必須擁有無可爭辯的數學證明。SMT 定理證明器是 FLOW 宇宙的最高法院，凡無證明者，一律否決。",
        .book_excerpt = "SMT 最高法院透過 QF_LIA 理論驗證緩衝區邊界、記憶體配額上限、分片隔離與確定性 4 大定理。合約檢查與硬體邊界在編譯期即刻生成 1-Cycle 多面體位元修剪遮罩。"
    },
    {
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "第六章：JIT 代碼發射與幾何變形 (AoS 到 SoA 即時重映射與生存模式)",
        .philosophy_why = "程式碼不是雕刻在石頭上的死文字，而是能在記憶體中自發變形的黏土。當記憶體即將崩潰時，系統在微秒內完成拓樸幾何變形，躲過 OS OOM Killer 的致命屠刀。",
        .book_excerpt = "JIT 發射器支援 C、Rust、Python 與 LLVM IR 多目標。透過 mremap 實現 AoS 與 SoA 零拷貝即時切換；在極端低記憶體下自我否決 JIT，遁入零分配 Static Survival 避難所。"
    },
    {
        .chapter_ref = "ch07_qsbr_lockfree_hotswap.md",
        .chapter_title = "第七章：QSBR 零鎖熱替換 (微秒級世代指針遷移與 Watchdog 隔離)",
        .philosophy_why = "在每秒數千萬次請求的高並發伺服器中，獲取哪怕一把讀寫鎖（RWLock）都會造成災難性的快取一致性風暴。FLOW 採用統一 QSBR 無鎖架構，實現了讀取路徑零原子寫入、熱替換微秒級無損遷移。",
        .book_excerpt = "QSBR 透過靜態世代演進實現 >390M ops/s 讀取吞吐量。看門狗以 mprotect 隔離掉隊讀者執行緒，以客製化信號捕捉保證優雅降級與 0 丟失請求熱替換。"
    },
    {
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "第九章：大一統 .fvec 與 Universal Lockfile (架構權重庫、零秒冷啟動與抗體昇華)",
        .philosophy_why = "大腦負責即時推論，而 .fvec 是大腦裡的長期記憶神經權重。它既是具備 SMT 物理簽章的 Universal Lockfile，也是在戰火中自主長出肌肉記憶的抗體庫。",
        .book_excerpt = "大一統 .fvec 採用 1024-Byte 明文 ASCII 表頭 + CRC32 載荷。1ms 硬體親和度門禁杜絕跨架構無效套用；在線 100 萬次請求零錯誤與 SMT 認證觸發抗體昇華與赫布強化。"
    },
    {
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "第十章：決定論因果推論大腦 (0% 幻覺的架構自省、神經遙測熱點與職責分離)",
        .philosophy_why = "我們不需要一個會胡言亂語的機率型 Chatbot 來解釋系統架構。FLOW 打造了 Flowy——一個內建於二進位中、100% 決定論、零幻覺的代碼庫因果推論大腦。",
        .book_excerpt = "Flowy 嚴格遵循大腦（flowy.c）、審計設施（audit.c）與前端表現層（flowy_cli.c）三層分離。即時解析決策因果（flowy why）、神經遙測熱點（flowy bottleneck）與反事實模擬。"
    },
    {
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "第十一章：Level 5 絕對死局壓測與效能基準 (並發風暴與 OOM 雙重束縛下的生存實錄)",
        .philosophy_why = "在科林丸號（Kobayashi Maru）測試中，學員面臨註定毀滅的死局。FLOW 打造了 Level 5 絕對死局壓測：當記憶體暴跌 99%、連線暴增 10,000 倍時，系統在死局中自我蛻變求生。",
        .book_excerpt = "Level-5 熔爐壓測驗證了系統在雙重束縛下的 5 階段自癒過程，維持 0 封包丟失與 0 崩潰；QSBR 讀取吞吐達到 390M ops/s，通用鎖定檔套用耗時縮短至 37 微秒。"
    }
};

static const FlowBookChapterDoc FLOW_BOOK_CHAPTERS_EN[FLOW_BOOK_CHAPTER_COUNT] = {
    {
        .chapter_ref = "ch01_what_is_flow.md",
        .chapter_title = "Chapter 1: What is FLOW? (Paradigm Shift from Static Compiler to Living System)",
        .philosophy_why = "We are not compiling dead code, but nurturing an autopoietic topological organism that senses environment, anneals autonomously, and morphs under destructive stress.",
        .book_excerpt = "Since the 1957 Fortran compiler, the assumption has been that source code is static truth. FLOW inverts this: code declares immutable geometric boundaries, while the runtime organism evolves on manifolds."
    },
    {
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "Chapter 2: Intent vs. Implementation (.flow: We Declare Invariants, Not Logic)",
        .philosophy_why = "In FLOW philosophy, writing code is not telling the CPU step-by-step instructions, but declaring the geometric boundaries and mathematical invariants the universe must obey.",
        .book_excerpt = "A standard .flow spec is strictly declarative with no imperative loops or manual pointers. Developers declare input bounds and pipeline topology, letting the engine synthesize optimal implementations."
    },
    {
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "Chapter 3: Topology Graph (Dimensionality Reduction into Computable Invariants)",
        .philosophy_why = "Software architecture is not a stack of directory text files, but a high-dimensional topology graph computed via graph theory, shard affinity, and neural telemetry.",
        .book_excerpt = "FLOW models compiler core, drivers, components, and intent as a unified FlowTopologyGraph, enforcing strict layer firewalls with 0 cross-layer architectural leaks."
    },
    {
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "Chapter 5: Formal Supreme Court (SMT 4-Theorem UNSAT Proofs & 1-Cycle Pruning)",
        .philosophy_why = "Heuristic search can explore freely, but every emitted line of machine code must have indisputable mathematical proofs. The SMT solver is the Supreme Court: unproven plans are vetoed.",
        .book_excerpt = "SMT proves buffer bounds, memory quotas, shard isolation, and determinism via QF_LIA. Contract and resource bounds immediately synthesize 1-cycle bitwise pruning masks."
    },
    {
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "Chapter 6: JIT Emission & Geometric Morphing (AoS to SoA Remapping & Survival Mode)",
        .philosophy_why = "Code is not carved in stone, but clay morphing in memory. When RAM collapses, the system executes microsecond geometric morphing to escape the OS OOM Killer.",
        .book_excerpt = "JIT emitter targets C, Rust, Python, and LLVM IR. mremap enables zero-copy AoS <-> SoA morphing. Under stress, self-aware JIT vetoes compilation and routes traffic to Static Survival shelters."
    },
    {
        .chapter_ref = "ch07_qsbr_lockfree_hotswap.md",
        .chapter_title = "Chapter 7: QSBR Lock-Free Hot-Swap (Sub-Microsecond Generational Migration)",
        .philosophy_why = "In servers processing millions of requests/sec, acquiring even one RWLock triggers catastrophic cache-line bouncing. FLOW QSBR achieves zero atomic writes on read paths and sub-microsecond migration.",
        .book_excerpt = "QSBR achieves >390M ops/s read throughput. Epoch watchdogs isolate stragglers via mprotect, guaranteeing graceful degradation and 0 dropped requests during hot-swap."
    },
    {
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "Chapter 9: Universal .fvec & Lockfiles (Architecture Weights, Zero-Cold-Start & Antibodies)",
        .philosophy_why = "The brain infers in real time, while .fvec stores long-term architecture weights. It serves as a Universal Lockfile with SMT signatures and an immune antibody repository.",
        .book_excerpt = "Universal .fvec pairs a 1024-byte ASCII header with CRC32 binary payload. A 1ms affinity gate rejects incompatible architectures; 1M zero-error online requests trigger autonomous antibody promotion."
    },
    {
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "Chapter 10: Deterministic Flowy Reasoner (0% Hallucination Introspection & Decoupling)",
        .philosophy_why = "We do not need a hallucinating probabilistic chatbot to explain system architecture. FLOW built Flowy: a 100% deterministic, zero-hallucination causal codebase reasoner in pure C.",
        .book_excerpt = "Flowy decouples Brain (flowy.c), Audit Logger (audit.c), and CLI Presentation (flowy_cli.c). It provides deterministic causal explanations (flowy why), telemetry diagnosis, and what-if simulation."
    },
    {
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "Chapter 11: Level 5 Crucible & Benchmarks (Kobayashi Maru & Production Replay)",
        .philosophy_why = "In Kobayashi Maru double-bind crises where memory drops 99% amid 10,000x traffic surges, FLOW demonstrates Level-5 resilience via SMT veto, JIT shelter, and QSBR zero-downtime morphing.",
        .book_excerpt = "The Level-5 crucible validates 5-stage autonomous self-healing with 0 dropped requests and 0 panics. QSBR achieves >390M ops/s read throughput and 37us instant cold-start application."
    }
};

typedef struct {
    const char *module_id;
    const char *chapter_ref;
    const char *chapter_title;
    const char *philosophy_why;
    const char *book_excerpt;
} FlowModuleBookBinding;

static const FlowModuleBookBinding FLOW_MODULE_BOOK_BINDINGS_ZH[28] = {
    {
        .module_id = "flowc",
        .chapter_ref = "ch01_what_is_flow.md",
        .chapter_title = "第一章：什麼是 FLOW？ (從靜態編譯到動態活體系統的典範轉移)",
        .philosophy_why = "我們不是在編譯一份死沉沉的程式碼，而是在孕育一個能夠感知環境、自我退火、在毀滅性壓力下自我蛻變的拓樸活體。",
        .book_excerpt = "自 1957 年 Fortran 編譯器問世以來，編譯器架構的核心假設始終如一：原始碼是唯一真理。FLOW 徹底顛覆此一假設，將代碼視為可感知環境與持續演化的活體幾何流形。"
    },
    {
        .module_id = "parser",
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "第二章：意圖規格 .flow (我們只向宇宙宣告幾何約束，不寫邏輯)",
        .philosophy_why = "在 FLOW 的哲學中，撰寫程式碼不是告訴 CPU 如何一步一步執行指令，而是向宇宙宣告系統必須服從的幾何邊界與不變量。",
        .book_excerpt = "一個標準的 .flow 描述檔是純宣告式的，不包含命令式迴圈或指標操作。開發者只宣告 input 規模、flow 流水線與物理約束，實作由引擎自動坍縮合成。"
    },
    {
        .module_id = "semantic",
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "第二章：意圖規格 .flow (我們只向宇宙宣告幾何約束，不寫邏輯)",
        .philosophy_why = "在 FLOW 的哲學中，撰寫程式碼不是告訴 CPU 如何一步一步執行指令，而是向宇宙宣告系統必須服從的幾何邊界與不變量。",
        .book_excerpt = "一個標準的 .flow 描述檔是純宣告式的，不包含命令式迴圈或指標操作。開發者只宣告 input 規模、flow 流水線與物理約束，實作由引擎自動坍縮合成。"
    },
    {
        .module_id = "topology",
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "第三章：拓樸圖譜 (將程式碼降維成可推算的依賴約束流形)",
        .philosophy_why = "軟體的架構不是文字檔目錄的堆疊，而是一張高維拓樸圖。在 FLOW 中，程式碼被降維成可直接進行圖論運算、親和性分析與遙測附著的活體神經圖譜。",
        .book_excerpt = "FLOW 將核心模組、驅動、元件與意圖統構為 FlowTopologyGraph，實施嚴格的分層防火牆審計、動態神經遙測附著與零跨層滲漏保證。"
    },
    {
        .module_id = "orchestrator",
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "第三章：拓樸圖譜 (將程式碼降維成可推算的依賴約束流形)",
        .philosophy_why = "軟體的架構不是文字檔目錄的堆疊，而是一張高維拓樸圖。在 FLOW 中，程式碼被降維成可直接進行圖論運算、親和性分析與遙測附著的活體神經圖譜。",
        .book_excerpt = "FLOW 將核心模組、驅動、元件與意圖統構為 FlowTopologyGraph，實施嚴格的分層防火牆審計、動態神經遙測附著與零跨層滲漏保證。"
    },
    {
        .module_id = "bitspace",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火 (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .module_id = "search",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火 (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .module_id = "swarm",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火 (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .module_id = "genetic",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "第四章：1-Bit 混沌退火 (暫存器位元翻轉、連鎖群與量子漂移)",
        .philosophy_why = "在維度的詛咒與上位效應壁壘面前，傳統遺傳交叉必然撕裂拓樸；FLOW 以 12.96 奈秒純暫存器 1-Bit 混沌微步與 SMT 超級位元原子翻轉，突破局部鞍點。",
        .book_excerpt = "1-Bit 狀態脊椎將系統維度壓縮為 64-bit 離散基因組，透過三層動態遮罩畫布（SMT 硬安全閘門、遙測偏置、領域偏好）在 1 個時鐘週期內修剪 99.9% 非法狀態，並以 9-Byte UDP 費洛蒙實現群體尋優。"
    },
    {
        .module_id = "smt",
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "第五章：形式化最高法院 (SMT 4 大定理 UNSAT 證明與 1-Cycle 修剪)",
        .philosophy_why = "啟發式搜尋可以天馬行空，但發射出的每一行機器碼必須擁有無可爭辯的數學證明。SMT 定理證明器是 FLOW 宇宙的最高法院，凡無證明者，一律否決。",
        .book_excerpt = "SMT 最高法院透過 QF_LIA 理論驗證緩衝區邊界、記憶體配額上限、分片隔離與確定性 4 大定理。合約檢查與硬體邊界在編譯期即刻生成 1-Cycle 多面體位元修剪遮罩。"
    },
    {
        .module_id = "verifier",
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "第五章：形式化最高法院 (SMT 4 大定理 UNSAT 證明與 1-Cycle 修剪)",
        .philosophy_why = "啟發式搜尋可以天馬行空，但發射出的每一行機器碼必須擁有無可爭辯的數學證明。SMT 定理證明器是 FLOW 宇宙的最高法院，凡無證明者，一律否決。",
        .book_excerpt = "SMT 最高法院透過 QF_LIA 理論驗證緩衝區邊界、記憶體配額上限、分片隔離與確定性 4 大定理。合約檢查與硬體邊界在編譯期即刻生成 1-Cycle 多面體位元修剪遮罩。"
    },
    {
        .module_id = "jit",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "第六章：JIT 代碼發射與幾何變形 (AoS 到 SoA 即時重映射與生存模式)",
        .philosophy_why = "程式碼不是雕刻在石頭上的死文字，而是能在記憶體中自發變形的黏土。當記憶體即將崩潰時，系統在微秒內完成拓樸幾何變形，躲過 OS OOM Killer 的致命屠刀。",
        .book_excerpt = "JIT 發射器支援 C、Rust、Python 與 LLVM IR 多目標。透過 mremap 實現 AoS 與 SoA 零拷貝即時切換；在極端低記憶體下自我否決 JIT，遁入零分配 Static Survival 避難所。"
    },
    {
        .module_id = "adaptive",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "第六章：JIT 代碼發射與幾何變形 (AoS 到 SoA 即時重映射與生存模式)",
        .philosophy_why = "程式碼不是雕刻在石頭上的死文字，而是能在記憶體中自發變形的黏土。當記憶體即將崩潰時，系統在微秒內完成拓樸幾何變形，躲過 OS OOM Killer 的致命屠刀。",
        .book_excerpt = "JIT 發射器支援 C、Rust、Python 與 LLVM IR 多目標。透過 mremap 實現 AoS 與 SoA 零拷貝即時切換；在極端低記憶體下自我否決 JIT，遁入零分配 Static Survival 避難所。"
    },
    {
        .module_id = "backend",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "第六章：JIT 代碼發射與幾何變形 (AoS 到 SoA 即時重映射與生存模式)",
        .philosophy_why = "程式碼不是雕刻在石頭上的死文字，而是能在記憶體中自發變形的黏土。當記憶體即將崩潰時，系統在微秒內完成拓樸幾何變形，躲過 OS OOM Killer 的致命屠刀。",
        .book_excerpt = "JIT 發射器支援 C、Rust、Python 與 LLVM IR 多目標。透過 mremap 實現 AoS 與 SoA 零拷貝即時切換；在極端低記憶體下自我否決 JIT，遁入零分配 Static Survival 避難所。"
    },
    {
        .module_id = "reload",
        .chapter_ref = "ch07_qsbr_lockfree_hotswap.md",
        .chapter_title = "第七章：QSBR 零鎖熱替換 (微秒級世代指針遷移與 Watchdog 隔離)",
        .philosophy_why = "在每秒數千萬次請求的高並發伺服器中，獲取哪怕一把讀寫鎖（RWLock）都會造成災難性的快取一致性風暴。FLOW 採用統一 QSBR 無鎖架構，實現了讀取路徑零原子寫入、熱替換微秒級無損遷移。",
        .book_excerpt = "QSBR 透過靜態世代演進實現 >390M ops/s 讀取吞吐量。看門狗以 mprotect 隔離掉隊讀者執行緒，以客製化信號捕捉保證優雅降級與 0 丟失請求熱替換。"
    },
    {
        .module_id = "primitive",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "abi",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "registry",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "security",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "embodied",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "第八章：硬體原語驅動 (奧坎剃刀下的 3-Function 極簡 ABI 與具身物理閘門)",
        .philosophy_why = "Plugin 不該是沉重的編譯器外掛，而只是大腦接在物理世界的視神經與肌肉。奧坎剃刀切除了一切非必要的 24 個回呼實體，只留下極簡的 3 個硬體原語驅動介面。",
        .book_excerpt = "極簡驅動 ABI 只需宣告硬體原語、呈報 SMT 物理邊界與執行調度。具身模組具備 1kHz 脊髓反射與 1Hz 皮層重構雙速率分離，ZMP 零力矩點物理閘門確保機器人永不倒地。"
    },
    {
        .module_id = "flowy_fvec",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "第九章：大一統 .fvec 與 Universal Lockfile (架構權重庫、零秒冷啟動與抗體昇華)",
        .philosophy_why = "大腦負責即時推論，而 .fvec 是大腦裡的長期記憶神經權重。它既是具備 SMT 物理簽章的 Universal Lockfile，也是在戰火中自主長出肌肉記憶的抗體庫。",
        .book_excerpt = "大一統 .fvec 採用 1024-Byte 明文 ASCII 表頭 + CRC32 載荷。1ms 硬體親和度門禁杜絕跨架構無效套用；在線 100 萬次請求零錯誤與 SMT 認證觸發抗體昇華與赫布強化。"
    },
    {
        .module_id = "fvec",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "第九章：大一統 .fvec 與 Universal Lockfile (架構權重庫、零秒冷啟動與抗體昇華)",
        .philosophy_why = "大腦負責即時推論，而 .fvec 是大腦裡的長期記憶神經權重。它既是具備 SMT 物理簽章的 Universal Lockfile，也是在戰火中自主長出肌肉記憶的抗體庫。",
        .book_excerpt = "大一統 .fvec 採用 1024-Byte 明文 ASCII 表頭 + CRC32 載荷。1ms 硬體親和度門禁杜絕跨架構無效套用；在線 100 萬次請求零錯誤與 SMT 認證觸發抗體昇華與赫布強化。"
    },
    {
        .module_id = "vault",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "第九章：大一統 .fvec 與 Universal Lockfile (架構權重庫、零秒冷啟動與抗體昇華)",
        .philosophy_why = "大腦負責即時推論，而 .fvec 是大腦裡的長期記憶神經權重。它既是具備 SMT 物理簽章的 Universal Lockfile，也是在戰火中自主長出肌肉記憶的抗體庫。",
        .book_excerpt = "大一統 .fvec 採用 1024-Byte 明文 ASCII 表頭 + CRC32 載荷。1ms 硬體親和度門禁杜絕跨架構無效套用；在線 100 萬次請求零錯誤與 SMT 認證觸發抗體昇華與赫布強化。"
    },
    {
        .module_id = "flowy",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "第十章：決定論因果推論大腦 (0% 幻覺的架構自省、神經遙測熱點與職責分離)",
        .philosophy_why = "我們不需要一個會胡言亂語的機率型 Chatbot 來解釋系統架構。FLOW 打造了 Flowy——一個內建於二進位中、100% 決定論、零幻覺的代碼庫因果推論大腦。",
        .book_excerpt = "Flowy 嚴格遵循大腦（flowy.c）、審計設施（audit.c）與前端表現層（flowy_cli.c）三層分離。即時解析決策因果（flowy why）、神經遙測熱點（flowy bottleneck）與反事實模擬。"
    },
    {
        .module_id = "flowy_cli",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "第十章：決定論因果推論大腦 (0% 幻覺的架構自省、神經遙測熱點與職責分離)",
        .philosophy_why = "我們不需要一個會胡言亂語的機率型 Chatbot 來解釋系統架構。FLOW 打造了 Flowy——一個內建於二進位中、100% 決定論、零幻覺的代碼庫因果推論大腦。",
        .book_excerpt = "Flowy 嚴格遵循大腦（flowy.c）、審計設施（audit.c）與前端表現層（flowy_cli.c）三層分離。即時解析決策因果（flowy why）、神經遙測熱點（flowy bottleneck）與反事實模擬。"
    },
    {
        .module_id = "audit",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "第十章：決定論因果推論大腦 (0% 幻覺的架構自省、神經遙測熱點與職責分離)",
        .philosophy_why = "我們不需要一個會胡言亂語的機率型 Chatbot 來解釋系統架構。FLOW 打造了 Flowy——一個內建於二進位中、100% 決定論、零幻覺的代碼庫因果推論大腦。",
        .book_excerpt = "Flowy 嚴格遵循大腦（flowy.c）、審計設施（audit.c）與前端表現層（flowy_cli.c）三層分離。即時解析決策因果（flowy why）、神經遙測熱點（flowy bottleneck）與反事實模擬。"
    },
    {
        .module_id = "benchmark",
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "第十一章：Level 5 絕對死局壓測與效能基準 (並發風暴與 OOM 雙重束縛下的生存實錄)",
        .philosophy_why = "在科林丸號（Kobayashi Maru）測試中，學員面臨註定毀滅的死局。FLOW 打造了 Level 5 絕對死局壓測：當記憶體暴跌 99%、連線暴增 10,000 倍時，系統在死局中自我蛻變求生。",
        .book_excerpt = "Level-5 熔爐壓測驗證了系統在雙重束縛下的 5 階段自癒過程，維持 0 封包丟失與 0 崩潰；QSBR 讀取吞吐達到 390M ops/s，通用鎖定檔套用耗時縮短至 37 微秒。"
    },
    {
        .module_id = "gateway",
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "第十一章：Level 5 絕對死局壓測與效能基準 (並發風暴與 OOM 雙重束縛下的生存實錄)",
        .philosophy_why = "在科林丸號（Kobayashi Maru）測試中，學員面臨註定毀滅的死局。FLOW 打造了 Level 5 絕對死局壓測：當記憶體暴跌 99%、連線暴增 10,000 倍時，系統在死局中自我蛻變求生。",
        .book_excerpt = "Level-5 熔爐壓測驗證了系統在雙重束縛下的 5 階段自癒過程，維持 0 封包丟失與 0 崩潰；QSBR 讀取吞吐達到 390M ops/s，通用鎖定檔套用耗時縮短至 37 微秒。"
    }
};

static const FlowModuleBookBinding FLOW_MODULE_BOOK_BINDINGS_EN[28] = {
    {
        .module_id = "flowc",
        .chapter_ref = "ch01_what_is_flow.md",
        .chapter_title = "Chapter 1: What is FLOW? (Paradigm Shift from Static Compiler to Living System)",
        .philosophy_why = "We are not compiling dead code, but nurturing an autopoietic topological organism that senses environment, anneals autonomously, and morphs under destructive stress.",
        .book_excerpt = "Since the 1957 Fortran compiler, the assumption has been that source code is static truth. FLOW inverts this: code declares immutable geometric boundaries, while the runtime organism evolves on manifolds."
    },
    {
        .module_id = "parser",
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "Chapter 2: Intent vs. Implementation (.flow: We Declare Invariants, Not Logic)",
        .philosophy_why = "In FLOW philosophy, writing code is not telling the CPU step-by-step instructions, but declaring the geometric boundaries and mathematical invariants the universe must obey.",
        .book_excerpt = "A standard .flow spec is strictly declarative with no imperative loops or manual pointers. Developers declare input bounds and pipeline topology, letting the engine synthesize optimal implementations."
    },
    {
        .module_id = "semantic",
        .chapter_ref = "ch02_intent_vs_implementation.md",
        .chapter_title = "Chapter 2: Intent vs. Implementation (.flow: We Declare Invariants, Not Logic)",
        .philosophy_why = "In FLOW philosophy, writing code is not telling the CPU step-by-step instructions, but declaring the geometric boundaries and mathematical invariants the universe must obey.",
        .book_excerpt = "A standard .flow spec is strictly declarative with no imperative loops or manual pointers. Developers declare input bounds and pipeline topology, letting the engine synthesize optimal implementations."
    },
    {
        .module_id = "topology",
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "Chapter 3: Topology Graph (Dimensionality Reduction into Computable Invariants)",
        .philosophy_why = "Software architecture is not a stack of directory text files, but a high-dimensional topology graph computed via graph theory, shard affinity, and neural telemetry.",
        .book_excerpt = "FLOW models compiler core, drivers, components, and intent as a unified FlowTopologyGraph, enforcing strict layer firewalls with 0 cross-layer architectural leaks."
    },
    {
        .module_id = "orchestrator",
        .chapter_ref = "ch03_topology_graph.md",
        .chapter_title = "Chapter 3: Topology Graph (Dimensionality Reduction into Computable Invariants)",
        .philosophy_why = "Software architecture is not a stack of directory text files, but a high-dimensional topology graph computed via graph theory, shard affinity, and neural telemetry.",
        .book_excerpt = "FLOW models compiler core, drivers, components, and intent as a unified FlowTopologyGraph, enforcing strict layer firewalls with 0 cross-layer architectural leaks."
    },
    {
        .module_id = "bitspace",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .module_id = "search",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .module_id = "swarm",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .module_id = "genetic",
        .chapter_ref = "ch04_1bit_chaos_engine.md",
        .chapter_title = "Chapter 4: 1-Bit Chaotic Annealing (Bit Flips, Linkage Groups & Quantum Drift)",
        .philosophy_why = "In face of epistasis barriers, traditional GA crossover tears topology. FLOW employs 12.96ns 1-bit chaotic mutations with SMT super-bit atomic flips to tunnel through saddle points.",
        .book_excerpt = "The 1-Bit state spine encodes dimensions into 64-bit genomes, pruning 99.9% illegal states in a single clock cycle via 3-Tier Mask Canvases, sharing convergence via 9-byte UDP pheromones."
    },
    {
        .module_id = "smt",
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "Chapter 5: Formal Supreme Court (SMT 4-Theorem UNSAT Proofs & 1-Cycle Pruning)",
        .philosophy_why = "Heuristic search can explore freely, but every emitted line of machine code must have indisputable mathematical proofs. The SMT solver is the Supreme Court: unproven plans are vetoed.",
        .book_excerpt = "SMT proves buffer bounds, memory quotas, shard isolation, and determinism via QF_LIA. Contract and resource bounds immediately synthesize 1-cycle bitwise pruning masks."
    },
    {
        .module_id = "verifier",
        .chapter_ref = "ch05_smt_formal_verification.md",
        .chapter_title = "Chapter 5: Formal Supreme Court (SMT 4-Theorem UNSAT Proofs & 1-Cycle Pruning)",
        .philosophy_why = "Heuristic search can explore freely, but every emitted line of machine code must have indisputable mathematical proofs. The SMT solver is the Supreme Court: unproven plans are vetoed.",
        .book_excerpt = "SMT proves buffer bounds, memory quotas, shard isolation, and determinism via QF_LIA. Contract and resource bounds immediately synthesize 1-cycle bitwise pruning masks."
    },
    {
        .module_id = "jit",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "Chapter 6: JIT Emission & Geometric Morphing (AoS to SoA Remapping & Survival Mode)",
        .philosophy_why = "Code is not carved in stone, but clay morphing in memory. When RAM collapses, the system executes microsecond geometric morphing to escape the OS OOM Killer.",
        .book_excerpt = "JIT emitter targets C, Rust, Python, and LLVM IR. mremap enables zero-copy AoS <-> SoA morphing. Under stress, self-aware JIT vetoes compilation and routes traffic to Static Survival shelters."
    },
    {
        .module_id = "adaptive",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "Chapter 6: JIT Emission & Geometric Morphing (AoS to SoA Remapping & Survival Mode)",
        .philosophy_why = "Code is not carved in stone, but clay morphing in memory. When RAM collapses, the system executes microsecond geometric morphing to escape the OS OOM Killer.",
        .book_excerpt = "JIT emitter targets C, Rust, Python, and LLVM IR. mremap enables zero-copy AoS <-> SoA morphing. Under stress, self-aware JIT vetoes compilation and routes traffic to Static Survival shelters."
    },
    {
        .module_id = "backend",
        .chapter_ref = "ch06_jit_and_geometric_morphing.md",
        .chapter_title = "Chapter 6: JIT Emission & Geometric Morphing (AoS to SoA Remapping & Survival Mode)",
        .philosophy_why = "Code is not carved in stone, but clay morphing in memory. When RAM collapses, the system executes microsecond geometric morphing to escape the OS OOM Killer.",
        .book_excerpt = "JIT emitter targets C, Rust, Python, and LLVM IR. mremap enables zero-copy AoS <-> SoA morphing. Under stress, self-aware JIT vetoes compilation and routes traffic to Static Survival shelters."
    },
    {
        .module_id = "reload",
        .chapter_ref = "ch07_qsbr_lockfree_hotswap.md",
        .chapter_title = "Chapter 7: QSBR Lock-Free Hot-Swap (Sub-Microsecond Generational Migration)",
        .philosophy_why = "In servers processing millions of requests/sec, acquiring even one RWLock triggers catastrophic cache-line bouncing. FLOW QSBR achieves zero atomic writes on read paths and sub-microsecond migration.",
        .book_excerpt = "QSBR achieves >390M ops/s read throughput. Epoch watchdogs isolate stragglers via mprotect, guaranteeing graceful degradation and 0 dropped requests during hot-swap."
    },
    {
        .module_id = "primitive",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "abi",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "registry",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "security",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "embodied",
        .chapter_ref = "ch08_hardware_primitive_drivers.md",
        .chapter_title = "Chapter 8: Hardware Primitive Drivers (3-Function Minimalist ABI & Embodied Gates)",
        .philosophy_why = "Plugins are not bloated compiler extensions, but sensory organs and muscles. Occam's razor purges 24 callbacks, retaining 3 minimalist primitive driver hooks.",
        .book_excerpt = "Minimalist driver ABI declares primitives, reports SMT bounds, and executes syscalls. Embodied intelligence features dual-rate 1kHz/1Hz reflexes, with ZMP stability gates preventing robot tip-overs."
    },
    {
        .module_id = "flowy_fvec",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "Chapter 9: Universal .fvec & Lockfiles (Architecture Weights, Zero-Cold-Start & Antibodies)",
        .philosophy_why = "The brain infers in real time, while .fvec stores long-term architecture weights. It serves as a Universal Lockfile with SMT signatures and an immune antibody repository.",
        .book_excerpt = "Universal .fvec pairs a 1024-byte ASCII header with CRC32 binary payload. A 1ms affinity gate rejects incompatible architectures; 1M zero-error online requests trigger autonomous antibody promotion."
    },
    {
        .module_id = "fvec",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "Chapter 9: Universal .fvec & Lockfiles (Architecture Weights, Zero-Cold-Start & Antibodies)",
        .philosophy_why = "The brain infers in real time, while .fvec stores long-term architecture weights. It serves as a Universal Lockfile with SMT signatures and an immune antibody repository.",
        .book_excerpt = "Universal .fvec pairs a 1024-byte ASCII header with CRC32 binary payload. A 1ms affinity gate rejects incompatible architectures; 1M zero-error online requests trigger autonomous antibody promotion."
    },
    {
        .module_id = "vault",
        .chapter_ref = "ch09_fvec_universal_lockfile.md",
        .chapter_title = "Chapter 9: Universal .fvec & Lockfiles (Architecture Weights, Zero-Cold-Start & Antibodies)",
        .philosophy_why = "The brain infers in real time, while .fvec stores long-term architecture weights. It serves as a Universal Lockfile with SMT signatures and an immune antibody repository.",
        .book_excerpt = "Universal .fvec pairs a 1024-byte ASCII header with CRC32 binary payload. A 1ms affinity gate rejects incompatible architectures; 1M zero-error online requests trigger autonomous antibody promotion."
    },
    {
        .module_id = "flowy",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "Chapter 10: Deterministic Flowy Reasoner (0% Hallucination Introspection & Decoupling)",
        .philosophy_why = "We do not need a hallucinating probabilistic chatbot to explain system architecture. FLOW built Flowy: a 100% deterministic, zero-hallucination causal codebase reasoner in pure C.",
        .book_excerpt = "Flowy decouples Brain (flowy.c), Audit Logger (audit.c), and CLI Presentation (flowy_cli.c). It provides deterministic causal explanations (flowy why), telemetry diagnosis, and what-if simulation."
    },
    {
        .module_id = "flowy_cli",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "Chapter 10: Deterministic Flowy Reasoner (0% Hallucination Introspection & Decoupling)",
        .philosophy_why = "We do not need a hallucinating probabilistic chatbot to explain system architecture. FLOW built Flowy: a 100% deterministic, zero-hallucination causal codebase reasoner in pure C.",
        .book_excerpt = "Flowy decouples Brain (flowy.c), Audit Logger (audit.c), and CLI Presentation (flowy_cli.c). It provides deterministic causal explanations (flowy why), telemetry diagnosis, and what-if simulation."
    },
    {
        .module_id = "audit",
        .chapter_ref = "ch10_deterministic_flowy_reasoner.md",
        .chapter_title = "Chapter 10: Deterministic Flowy Reasoner (0% Hallucination Introspection & Decoupling)",
        .philosophy_why = "We do not need a hallucinating probabilistic chatbot to explain system architecture. FLOW built Flowy: a 100% deterministic, zero-hallucination causal codebase reasoner in pure C.",
        .book_excerpt = "Flowy decouples Brain (flowy.c), Audit Logger (audit.c), and CLI Presentation (flowy_cli.c). It provides deterministic causal explanations (flowy why), telemetry diagnosis, and what-if simulation."
    },
    {
        .module_id = "benchmark",
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "Chapter 11: Level 5 Crucible & Benchmarks (Kobayashi Maru & Production Replay)",
        .philosophy_why = "In Kobayashi Maru double-bind crises where memory drops 99% amid 10,000x traffic surges, FLOW demonstrates Level-5 resilience via SMT veto, JIT shelter, and QSBR zero-downtime morphing.",
        .book_excerpt = "The Level-5 crucible validates 5-stage autonomous self-healing with 0 dropped requests and 0 panics. QSBR achieves >390M ops/s read throughput and 37us instant cold-start application."
    },
    {
        .module_id = "gateway",
        .chapter_ref = "ch11_level5_crucible_and_benchmarks.md",
        .chapter_title = "Chapter 11: Level 5 Crucible & Benchmarks (Kobayashi Maru & Production Replay)",
        .philosophy_why = "In Kobayashi Maru double-bind crises where memory drops 99% amid 10,000x traffic surges, FLOW demonstrates Level-5 resilience via SMT veto, JIT shelter, and QSBR zero-downtime morphing.",
        .book_excerpt = "The Level-5 crucible validates 5-stage autonomous self-healing with 0 dropped requests and 0 panics. QSBR achieves >390M ops/s read throughput and 37us instant cold-start application."
    }
};

static inline const FlowModuleBookBinding *flow_book_lookup_binding_lang(const char *module_id, FlowLanguage lang) {
    if (module_id == NULL) return NULL;
    const FlowModuleBookBinding *bindings = (lang == FLOW_LANG_EN) ? FLOW_MODULE_BOOK_BINDINGS_EN : FLOW_MODULE_BOOK_BINDINGS_ZH;
    for (size_t i = 0; i < 28; ++i) {
        if (strcmp(bindings[i].module_id, module_id) == 0) return &bindings[i];
    }
    return NULL;
}

static inline const FlowModuleBookBinding *flow_book_lookup_binding(const char *module_id) {
    return flow_book_lookup_binding_lang(module_id, FLOW_LANG_ZH);
}

static inline const FlowBookChapterDoc *flow_book_lookup_chapter_lang(const char *ref_or_name, FlowLanguage lang) {
    if (ref_or_name == NULL) return NULL;
    const FlowBookChapterDoc *chapters = (lang == FLOW_LANG_EN) ? FLOW_BOOK_CHAPTERS_EN : FLOW_BOOK_CHAPTERS_ZH;
    for (size_t i = 0; i < FLOW_BOOK_CHAPTER_COUNT; ++i) {
        if (strcmp(chapters[i].chapter_ref, ref_or_name) == 0 || strstr(chapters[i].chapter_title, ref_or_name) != NULL) {
            return &chapters[i];
        }
    }
    return NULL;
}

static inline const FlowBookChapterDoc *flow_book_lookup_chapter(const char *ref_or_name) {
    return flow_book_lookup_chapter_lang(ref_or_name, FLOW_LANG_ZH);
}

#endif /* FLOW_GENERATED_BOOK_KNOWLEDGE_H */
